### ISSUE TITLE
🚀 Feat: Implement Shop Admin Pages

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#137]
## Description

- Use this [Figma Design](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-10032&mode=design&t=aT0K9M6xTelIvnMc-0) to implement Shop Admin Pages.

## Tasks

- The pages below are to be added under `pages/admin/shop` directory:
  - [ ] [Dashboard](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-10105&mode=design&t=aT0K9M6xTelIvnMc-0)
  - [ ] [Orders Report](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-10945&mode=design&t=aT0K9M6xTelIvnMc-0)
  - [ ] [Sales Report](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-11173&mode=design&t=aT0K9M6xTelIvnMc-0)
    - [ ] [Sales](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-10051&mode=design&t=aT0K9M6xTelIvnMc-0) & [Order](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-11832&mode=design&t=aT0K9M6xTelIvnMc-0) Statement Components (`components/admin/shop` directory)
  - [ ] [Inventory Report](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-11401&mode=design&t=aT0K9M6xTelIvnMc-0)
  - [ ] [Single Sales Item](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-11603&mode=design&t=aT0K9M6xTelIvnMc-0)
    - [ ] [Edit Item](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-11940&mode=design&t=aT0K9M6xTelIvnMc-0) and [Add Item](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=5494-10033&mode=design&t=aT0K9M6xTelIvnMc-0) Components (`components/admin/shop` directory)
  

-   In the `router/index.jsx` file, add the shop routes:
```jsx
// /router/index.jsx
// ...other code

  {
     path: "/admin",
     element: <AdminLayout />,
     children: [
      {
        path: "/admin/shop",
        element: <ShopDashboard />, // Shop Dashboard page you're building
      },
      {
        path: "/admin/shop/orders-report",
        element: <OrdersReport/>, // Order page you're building
      },
      {
        path: "/admin/shop/sales-report",
        element: <SalesReport/>, // Sales page you're building
      },
      {
        path: "/admin/shop/inventory-report",
        element: <InventoryReport/>, // Inventory page you're building
      },
      {
        path: "/admin/shop/sales-report/:id",
        element: <SingleSalesItem/>, // Singel Sales Item page you're building
      },

// ...other routes
  ]
}
```
Feel free to name the components and pages as you see fit. 😁
