### ISSUE TITLE
Replace `fontawesome` icons and svg icons with `react-icons`

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#170]
## Description
In efforts to make the repo lighter, we'll be dropping some redundant package dependencies. `react-icons` has a wider variety of icons compared to the `fontawesome` version we're using.

## Tasks

- [ ] Install `react-icons`
- [ ] Replace every `fontawesome` icon with a similar icon from `react-icons`
- [ ] Replace all icons that were imported as .svg files with similar icons from `react-icons` if possible
- [ ] Uninstall `@fortawesome/fontawesome-svg-core`, `@fortawesome/free-solid-svg-icons` and `@fortawesome/react-fontawesome` dependencies

**Comment by Benewaza** [comment]
Hi, il take this issue if it still needs completing.

**Comment by sonylomo** [comment]
Hey @Benewaza 👋🏾 

This issue has already been assigned to someone else. However, we still have new issues coming up within the week.

Be on the lookout for them. 🙂

**Comment by sonylomo** [comment]
Fixed by PR #178
