### ISSUE TITLE
Delete unused asset images from the repo

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#171]
## Description
In efforts to make the repo lighter, we'll be dropping some redundant files. There are some files in the assets folder that are not being used.

## Tasks

- [x] Delete unused assets
- [x] Ensure the naming convention for the files is hyphenated and lowercase
- [x] Categorize the files according to the pages they're used in e.g `assets/images/about` folder for the About page assets

**Comment by CodedVeli** [comment]
task complete
