### ISSUE TITLE
Redesign Shop: Landing Page

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#196]
## Description
There's an older version of Landing Page on `./pages/shop/sections/CategoriesProducts` and `./pages/shop/Homepage` files. You could try refactoring it to [this Figma Design](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=10310-6555&t=BKQWYyXN1n1b57Kn-0) for the Shop Landing Page.

## Tasks

- [ ] Implement Hero carousel, filter/search functionality and FAQ; in the same format as the existing components from the `/events` and `/` pages.
- [ ] Create a reusable shop item card 
- [ ] Make the UI responsive on mobile
