### ISSUE TITLE
Admin Shop Pages: Inventory Report

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#202]
## Description
Refer to [this Figma Design](https://www.figma.com/design/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?node-id=5494-11401&t=PNsF2qBBc3xyzFjV-0) for the Inventory Report Page.

Please use [`Shadcn`](https://ui.shadcn.com/docs/components/data-table) for the Data Table and [`Recharts`](https://recharts.org/?p=/en-US/guide) for charts. Otherwise, please use Tailwind CSS styles.

## Tasks

- [x] Implement the designs referenced above (Inventory Report and Add Item Form)
- [x] Implement form validation to Add Item Form using `react-hook-form`
- [x] Make it responsive on mobile if possible

**Comment by avinash-24-aptrix** [comment]
Using Tailwind CSS
I can efficiently use Tailwind CSS for styling, providing quick and responsive designs. With Tailwind’s utility-first approach, I apply styling directly in HTML, making development faster and more flexible. Whether setting up new projects or integrating into existing ones, I ensure optimal configuration and customization to match your needs. Tailwind's responsive utilities and production optimizations, like PurgeCSS, help create sleek, scalable, and efficient web applications.

**Comment by CodedVeli** [comment]
All three tasks are complete
