### ISSUE TITLE
Admin Shop Pages: Single Inventory Item View Page

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#203]
## Description
Refer to [this Figma Design](https://www.figma.com/design/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?node-id=5494-11603&t=PNsF2qBBc3xyzFjV-0) for the Single Inventory Item View Page.

Please use [`Shadcn`](https://ui.shadcn.com/docs/components/data-table) for the Data Table and [`Recharts`](https://recharts.org/?p=/en-US/guide) for charts. Otherwise, please use Tailwind CSS styles.

## Tasks

- [ ] Implement the designs referenced above (Single Inventory Item and Edit Item Form)
- [ ] Add form validation to Edit Item Form with `react-hook-form`
- [ ] Make it responsive on mobile if possible

**Comment by sonylomo** [comment]
@Avinashshiyani, would you be interested in this issue? 👀

**Comment by Avinashshiyani** [comment]
> @Avinashshiyani, would you be interested in this issue? 👀

Of cource yes for me it's a great opportunity .
