### ISSUE TITLE
Feat: Implement Mastercraft Landing Page

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#233]
## Description

We're developing the _MasterCraft program_ landing page under `/resources`. This is the [Figma Design](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=10562-11352&t=P3sWZNWyNCxCKf8n-0#910522525) that needs to be implemented.

## Tasks

- [ ] Implement the design above
- [ ] Make it responsive on mobile
- [ ] Write tests(`Playwright/Vitest`) for the page
