### ISSUE TITLE
MVP: Navbar fixes

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#72]
## Description

- The active Navbar links don't turn green when you navigate between pages. 
- For the MVP, we'll only need these pages on the navbar:
   - Home
   - About Us
   - Community

## Tasks

- [x] Display the active navbar link for the current page
- [x] Add a max-width for large screen displays (about 1920px)
- [x] Comment out nav links that are not required for the MVP

**Comment by Ase020** [comment]
commented out the currently unneeded navlinks
